title: 荟聚
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
